sudo: required

language: go

services:
  - docker

install:
- docker build -t brint/docker-box .

script:
- docker run brint/docker-box go version
- docker run brint/docker-box docker
- docker run brint/docker-box docker-machine --version
- docker run brint/docker-box docker-compose version
